# DEEP LEARNING 
## Pytorch cơ bản
 


In [65]:
import torch 

In [66]:
torch.cuda.is_available()

True

Sử dụng GPU và Cuda 

In [67]:
torch.cuda.current_device()

0

Dataset with pytorch

In [68]:
import torch
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [69]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [70]:
df.shape

(150, 6)

In [71]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis = 1).values
y= le.fit_transform(df["Species"].values) 


# chia dữ liệu với test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.2, random_state=42 )
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)


In [72]:
len(y_train)  # 80% của 150

120

In [73]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


Tính đạo hàm bằng pytorch
cho y = 2x^4 + x^3 + 3x^2 + 5x + 1
tính y'

In [74]:
import torch 


In [75]:
x= torch.tensor(2.0, requires_grad = True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [76]:
# định nghĩa hàm 
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1 
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [77]:
y.grad_fn

In [78]:
# thực hiện lan truyền ngược và tính toán các gradient
y.backward()

In [79]:
x.grad

tensor(93.)

### BTVN1 : cho y = 5x^5 + 6x^3 - 3x + 1. cho biết độ dốc của đa thức trên ở điểm nào.




In [80]:
import torch
x = torch.tensor(2.0, requires_grad=True)
y = 5*x**5 + 6*x**3 - 3*x + 1
y.grad_fn
y.backward()
x.grad
print("Độ dốc tại x = 2: ",x.grad.item()) #x bằng bao nhiêu thì độ dốc của đa thức ở điểm x đó 

Độ dốc tại x = 2:  469.0


### BTVN2 : tạo 1 tensor ban đầu có giá trị là 2. định nghĩa hàm số và tính gradient 
y = x^3 + 2x^2 + 5x + 1. hãy tính dy/dx tại giá trị của x 
dùng phương pháp gradient descent với: learning_rate alpha =0.1 để cập nhật giá trị x trong 10 vòng lặp


In [81]:
import torch
x = torch.tensor(2.0, requires_grad=True)
learning_rate_alpha = 0.1
for i in range(10):
    y = x**3 + 2*x**2 + 5*x + 1 
    y.backward()
    with torch.no_grad():
        x -= learning_rate_alpha * x.grad  #cập nhật x theo công thức gradient descent
        x.grad.zero_() # reset gradient để tránh cộng dồn
    print(f'Iter {i+1} : x = {x.item()}')

Iter 1 : x = -0.5
Iter 2 : x = -0.875
Iter 3 : x = -1.2546875476837158
Iter 4 : x = -1.7250847816467285
Iter 5 : x = -2.427826166152954
Iter 6 : x = -3.7249975204467773
Iter 7 : x = -6.897680282592773
Iter 8 : x = -18.912006378173828
Iter 9 : x = -119.14640808105469
Iter 10 : x = -4330.74755859375


### BTVN3: tạo 1 tập dữ liệu giả lập với x là số giờ học ngẫu nhiên từ 1 đến 10 và y là số điểm đc tính theo công thức y = 3x + 5+ noise , với noise là 1 giá trị ngẫu nhiên nhỏ 
1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad= true
2. tính MSE
3. Tính gradient
4. Cập nhật tham số w và b bằng gradient Descent với Learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình

In [82]:
import torch
x = torch.rand(10,1) * 9 + 1  #tạo 10 gtri x ngẫu nhiên tù 1 đến 10
noise = torch.randn(1) # tạo 1 gtri noise ngẫu nhiên nhỏ
y =  3*x + 5 + noise

# 1. khởi tạo tham số w và b ngẫu nhiên 
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f'tập gtri x: ',"\n", f'{x}')
print(f'noise : {noise}')
print(f'y = {y}')
print(f'w : {w.item()}')
print(f'b : {b.item()}')


tập gtri x:  
 tensor([[8.9191],
        [9.6942],
        [2.6706],
        [8.0990],
        [1.9970],
        [7.1976],
        [6.5487],
        [1.9168],
        [2.0230],
        [9.3176]])
noise : tensor([1.5112])
y = tensor([[33.2685],
        [35.5938],
        [14.5230],
        [30.8082],
        [12.5023],
        [28.1039],
        [26.1572],
        [12.2615],
        [12.5803],
        [34.4640]])
w : -0.7068402171134949
b : 1.1791833639144897


In [83]:
#2. tính MSE
y_pred = w * x + b  # dự đoán theo mô hình tuyến tính
loss = ((y_pred - y) ** 2).mean()  # cthuc mse = trung bình **2 sai số

print("MSE : ", loss.item())

MSE :  863.1455078125


In [84]:
#3. Tính gradient
loss.backward()  #tính grad của loss theo w và b
print(f'gradient w : {w.grad.item()}')
print(f'gradient b : {b.grad.item()}')

gradient w : -388.1036682128906
gradient b : -53.94778060913086


In [85]:
print(w.grad)

tensor([-388.1037])


In [86]:
#4. Cập nhật tham số w và b bằng gradient Descent với Learning rate alpha = 0.01
lr_alpha = 0.01
with torch.no_grad():
    w -= lr_alpha * w.grad
    b -= lr_alpha * b.grad

    w.grad.zero_()
    b.grad.zero_()
print(f'w cập nhật: {w.item()} ')
print(f'b cập nhật: {b.item()} ')

w cập nhật: 3.174196243286133 
b cập nhật: 1.7186610698699951 


In [87]:
#5. Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình
for epoch in range(100):
    y_pred = w * x + b  # dự đoán theo mô hình tuyến tính
    loss = ((y_pred - y) ** 2).mean()  # cthuc mse = trung bình **2 sai số
    loss.backward() 

    lr_alpha = 0.01
    with torch.no_grad():
        w -= lr_alpha * w.grad
        b -= lr_alpha * b.grad

        w.grad.zero_()
        b.grad.zero_()
    print(f"Epoch {epoch}: Loss = {loss.item()}")

Epoch 0: Loss = 14.554235458374023
Epoch 1: Loss = 5.086970329284668
Epoch 2: Loss = 4.938483238220215
Epoch 3: Loss = 4.89385986328125
Epoch 4: Loss = 4.850768089294434
Epoch 5: Loss = 4.808069705963135
Epoch 6: Loss = 4.765749931335449
Epoch 7: Loss = 4.723799705505371
Epoch 8: Loss = 4.682217597961426
Epoch 9: Loss = 4.641002655029297
Epoch 10: Loss = 4.600153923034668
Epoch 11: Loss = 4.559659481048584
Epoch 12: Loss = 4.519524097442627
Epoch 13: Loss = 4.47974157333374
Epoch 14: Loss = 4.440310478210449
Epoch 15: Loss = 4.401224613189697
Epoch 16: Loss = 4.362483024597168
Epoch 17: Loss = 4.324082851409912
Epoch 18: Loss = 4.286020278930664
Epoch 19: Loss = 4.248293399810791
Epoch 20: Loss = 4.210898399353027
Epoch 21: Loss = 4.173834323883057
Epoch 22: Loss = 4.137092113494873
Epoch 23: Loss = 4.100676536560059
Epoch 24: Loss = 4.06458044052124
Epoch 25: Loss = 4.028801918029785
Epoch 26: Loss = 3.9933407306671143
Epoch 27: Loss = 3.9581902027130127
Epoch 28: Loss = 3.92334794998

In [88]:
# torch with tensor 

In [89]:
import torch 
import numpy as np 


In [90]:
torch.__version__

'2.5.1+cu121'

In [91]:
# chuyển đổi mảng numoy sang tensor pytorch 
arr = np.array([1,2,3,4,5])
print (arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [92]:
x = torch.from_numpy(arr)
print(x)

print(x.dtype)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)
torch.int32


In [93]:
print(x.type())

torch.IntTensor


In [94]:
arr2 = np.arange(0., 12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [95]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [96]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [97]:
arr[0]= 99
print(x)

tensor([99,  2,  3,  4,  5], dtype=torch.int32)


In [98]:
arr = np.arange(0, 5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [99]:
arr[0] = 99 
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


## BTVN4: giải thích 2 trường hợp trên
- Trường hợp 1: torch.from_numpy(arr): Tensor và Numpy dùng chung bộ nhớ nên  khi thay đổi arr thì x cũng thay đổi luôn
- Trường hợp 2: torch.tensor(arr): trường hợp này do tạo Tensor mới (copy dữ liệu) từ arr = np.arange(0,5) nên khi thay đổi arr thì x không đổi.

## BTVN5: bạn giúp thầy tạo tensor với : 
1. Empyty
2. Zeros
3. Ones
4. Random
4. Reshape với view và view as

In [100]:
import torch

In [101]:
# 1. empyty
empyty = torch.empty(2, 3)
print(empyty)

tensor([[9.3598e-36, 1.3775e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [102]:
# 2. zeros
zeros = torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [103]:
# 3 ones
ones = torch.ones(2,3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [104]:
# 4. random
rand = torch.rand(2,3)
print(rand)

tensor([[0.3052, 0.4400, 0.4276],
        [0.5813, 0.2630, 0.9848]])


In [105]:
# 5. reshape
rs = torch.arange(6)                        

reshape = rs.view_as(rs.view(2,3))             
print(reshape)

tensor([[0, 1, 2],
        [3, 4, 5]])
