# DEEP LEARNING
## TUẦN 2 : NUMPY, PANDAS, MATPLOTLOB

## NUMPY

In [ ]:
# Numpy : là thư viện kiểu list, vì :
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI
# Để dùng numpy thì: pip install numpy
import numpy as np


In [ ]:
# tạo 1 danh sách
py_list =[1,2,3,4,5]

#chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(py_list)

type(numpy_list)


numpy.ndarray

In [ ]:
# list trong python có thể hỗ trợ nhiều kiểu dự liệu trong list
my_list = [1, "chào", True, 2.1]

In [ ]:
my_list = [1,2,3,4,5]
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

In [ ]:
# chuyển đổi kiểu dữ liệu
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4, 5])

In [ ]:
# accessing và indexing
x = np.array([1,2,3,4,5,6,7,8,9,10])  # x = np.array(range(1,9))

In [ ]:
# lấy số 4
x[3]

np.int64(4)

In [ ]:
# lấy nhiều hơn 1 phần tử
# công thức [start:end:step]
x[0:3:1]


array([1, 2, 3])

In [ ]:
#lấy tù 3 tới 8 theo 3 cách
x[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# láy 2 số 3 và 5
x[2], x[4]


(np.int64(3), np.int64(5))

In [ ]:
#đặt danh sách cách index muốn truy cập
x[[2,4]]

array([3, 5])

In [ ]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# lấy số 2
np_list[0,1]


np.int64(2)

In [ ]:
np_list[2,1]

np.int64(6)

In [ ]:
# lấy [3,4] [5, 6]
np_list[1:,:]


array([[3, 4],
       [5, 6]])

In [ ]:
# cách 2
np_list[[1, 2], :]

array([[3, 4],
       [5, 6]])

In [ ]:
# cách 3
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [ ]:
# lấy 1 3 5
np_list[:, 0]

array([1, 3, 5])

In [ ]:
# lấy 1 và 5 theo 2 cách
# cách 1
np_list[[0,2], 0]


array([1, 5])

In [ ]:
#cách 2
np_list[0::2, 0]


array([1, 5])

In [ ]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list=np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# lấy 2 6 10 14
np_list[:,1]

array([ 2,  6, 10, 14])

In [ ]:
# lấy 7 11
np_list[[1,2],2]

array([ 7, 11])

In [ ]:
# lấy  4 7 10
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [ ]:
# lấy 16 15 14 13
np_list[[3,3,3,3], [3,2,1,0]]

array([16, 15, 14, 13])

In [ ]:
# cách 2
np_list[3,::-1]

array([16, 15, 14, 13])

In [ ]:
# cách 3
np_list[-1,::-1]

array([16, 15, 14, 13])

### BTVN1: Cho ma trận  
```
= [
    [99,99,99],
    [99,99,99],
    [99,99,99]
]
```

+ hãy tưởng tượng ô 99 trống
+ giả sử 1 là x
+ giả sử 0 là o

+ lấy đầu vào từ phía X và phía o luân phiên
+ nếu đầu vào từ phía X là (0,0) thì ma trận sẽ trở thành
[[99,99,99],
[99,99,99],
[99,99,99]]
+ nếu đầu vào từ phía o cũng là (0,0) thì thông báo nhập lại, nếu không thì điền vào ma trận
+ thử thách, nếu người đầu tiên có 3 phần tử thì dừng trò chơi.

In [ ]:
import numpy as np

# Khởi tạo ma trận 3x3 với giá trị 99 (trống)
board = np.full((3, 3), 99, dtype=int)

# Định nghĩa người chơi
PLAYER_X = 1
PLAYER_O = 0
EMPTY = 99

# Hàm để in bảng
def print_board(board):
    symbols = {PLAYER_X: 'X', PLAYER_O: 'O', EMPTY: ' '}
    for row in board:
        print("| " + " | ".join(symbols[cell] for cell in row) + " |")
        print("-----------")

# Hàm kiểm tra chiến thắng
def check_win(board, player):
    # Kiểm tra hàng ngang
    for row in board:
        if np.all(row == player):
            return True
    # Kiểm tra cột dọc
    for col in board.T:
        if np.all(col == player):
            return True
    # Kiểm tra đường chéo chính
    if np.all(np.diag(board) == player):
        return True
    # Kiểm tra đường chéo phụ
    if np.all(np.diag(np.fliplr(board)) == player):
        return True
    return False

# Hàm kiểm tra hòa
def check_draw(board):
    return EMPTY not in board

# Bắt đầu trò chơi
current_player = PLAYER_X
print("Bắt đầu trò chơi Cờ caro (Tic-Tac-Toe)!")
print_board(board)

while True:
    try:
        player_symbol = 'X' if current_player == PLAYER_X else 'O'
        print(f"Lượt của người chơi {player_symbol}:")
        row = int(input("Nhập hàng (0, 1, hoặc 2): "))
        col = int(input("Nhập cột (0, 1, hoặc 2): "))

        # Kiểm tra tính hợp lệ của nước đi
        if not (0 <= row <= 2 and 0 <= col <= 2):
            print("Nước đi không hợp lệ. Hàng và cột phải nằm trong khoảng từ 0 đến 2.")
            continue
        if board[row, col] != EMPTY:
            print("Ô này đã có người chiếm. Vui lòng chọn ô khác.")
            continue

        # Cập nhật bảng
        board[row, col] = current_player
        print_board(board)

        # Kiểm tra chiến thắng
        if check_win(board, current_player):
            print(f"Chúc mừng người chơi {player_symbol} đã thắng cuộc!")
            break

        # Kiểm tra hòa
        if check_draw(board):
            print("Trò chơi hòa!")
            break

        # Chuyển lượt chơi
        current_player = PLAYER_O if current_player == PLAYER_X else PLAYER_X

    except ValueError:
        print("Đầu vào không hợp lệ. Vui lòng nhập số nguyên.")
    except Exception as e:
        print(f"Đã xảy ra lỗi: {e}")


Bắt đầu trò chơi Cờ caro (Tic-Tac-Toe)!
|   |   |   |
-----------
|   |   |   |
-----------
|   |   |   |
-----------
Lượt của người chơi X:
Nhập hàng (0, 1, hoặc 2): 0
Nhập cột (0, 1, hoặc 2): 0
| X |   |   |
-----------
|   |   |   |
-----------
|   |   |   |
-----------
Lượt của người chơi O:
Nhập hàng (0, 1, hoặc 2): 1
Nhập cột (0, 1, hoặc 2): 1
| X |   |   |
-----------
|   | O |   |
-----------
|   |   |   |
-----------
Lượt của người chơi X:
Nhập hàng (0, 1, hoặc 2): 1
Nhập cột (0, 1, hoặc 2): 0
| X |   |   |
-----------
| X | O |   |
-----------
|   |   |   |
-----------
Lượt của người chơi O:
Nhập hàng (0, 1, hoặc 2): 2
Nhập cột (0, 1, hoặc 2): 0
| X |   |   |
-----------
| X | O |   |
-----------
| O |   |   |
-----------
Lượt của người chơi X:
Nhập hàng (0, 1, hoặc 2): 0
Nhập cột (0, 1, hoặc 2): 2
| X |   | X |
-----------
| X | O |   |
-----------
| O |   |   |
-----------
Lượt của người chơi O:
Nhập hàng (0, 1, hoặc 2): 0
Nhập cột (0, 1, hoặc 2): 1
| X | O | X |
----------

In [ ]:
# BTVN2:
import numpy as np
y = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
# lấy 4 5 6
# lấy 2, 5
# lấy 3 4
# lấy 9 6 3

np_list= np.array(y)
np_list[1, ::1 ]


array([4, 5, 6])

In [ ]:
np_list[[0,1], [1,1]]

array([2, 5])

In [ ]:
np_list[::-1, -1]

array([9, 6, 3])

In [ ]:
## BTVN3:
# cho x = [1,2,3,4,5,6,7,8,9,10]
# 1. xuất ra các giá trị chẵn sử dụng if
# 2. xuất ra các giá trị chẵn sử dụng list comprehension


In [ ]:
# xuất ra các giá trị chẵn sử dụng if
x = [1,2,3,4,5,6,7,8,9,10]
for i in x:
    if i % 2 == 0:
        print(i)

2
4
6
8
10


In [ ]:
# xuất các giá trị chẵn sử dụng list comprehension

x = [1,2,3,4,5,6,7,8,9,10]
[i for i in x if i % 2 == 0]


[2, 4, 6, 8, 10]

In [ ]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_x[np_x % 2 == 0]


array([0, 2, 4, 6, 8])

In [ ]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
idx =[ True, False,  True, False,  True, False,  True, False,  True,
       False]
np_x[idx]

array([0, 2, 4, 6, 8])

In [ ]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
cond1 =  np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# BTVN:
# tạo một mảng numpy có kích thước 150 x 5. Gỉa sử mảng này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao , cân nặng, tuổi, lương và điểm trung bình
# tách mảng dựa trến 4 cột đầu tiên thành 1 biến có tên là X và cột cuối cùng thành y
# tách X thành X_train và X_test trong đó X_train chứa 70% dữ liệu và tách y thành y_train và y_test trong đó y_train chứa 70% dữ liệu
# tạo 10 tập dữ liệu X_train không chồng chéo nhau

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

# 1. Tạo một mảng numpy có kích thước 150 x 5 với dữ liệu ngẫu nhiên
# Sử dụng np.random.rand để tạo dữ liệu ngẫu nhiên giữa 0 và 1, sau đó nhân với một số để có phạm vi dữ liệu hợp lý (ví dụ: chiều cao, cân nặng, v.v.)
data_array = np.random.rand(150, 5)
print("Mảng dữ liệu ban đầu (150x5):")
print(data_array[:5]) # In ra 5 hàng đầu để xem trước

Mảng dữ liệu ban đầu (150x5):
[[0.56851014 0.96988593 0.35756266 0.30096889 0.56404307]
 [0.05972861 0.65353213 0.86457674 0.79560267 0.42018718]
 [0.49856702 0.64604228 0.60075523 0.07753742 0.65613149]
 [0.79405074 0.69805767 0.32869261 0.43980531 0.1745073 ]
 [0.95994013 0.1749205  0.42803189 0.45547841 0.66681745]]


In [ ]:
# 2. Tách mảng dựa trên 4 cột đầu tiên thành X và cột cuối cùng thành y
X = data_array[:, :4]
y = data_array[:, 4]

print("\nKích thước của X (các đặc trưng):", X.shape)
print(X[:5])
print("\nKích thước của y (nhãn/mục tiêu):", y.shape)
print(y[:5])


Kích thước của X (các đặc trưng): (150, 4)
[[0.56851014 0.96988593 0.35756266 0.30096889]
 [0.05972861 0.65353213 0.86457674 0.79560267]
 [0.49856702 0.64604228 0.60075523 0.07753742]
 [0.79405074 0.69805767 0.32869261 0.43980531]
 [0.95994013 0.1749205  0.42803189 0.45547841]]

Kích thước của y (nhãn/mục tiêu): (150,)
[0.56404307 0.42018718 0.65613149 0.1745073  0.66681745]


In [ ]:
# 3. Tách X thành X_train và X_test (70% dữ liệu cho X_train)
# 4. Tách y thành y_train và y_test (70% dữ liệu cho y_train)
# Sử dụng train_test_split từ sklearn để thực hiện việc này

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("\nKích thước của X_train:", X_train.shape)
print("Kích thước của X_test:", X_test.shape)
print("Kích thước của y_train:", y_train.shape)
print("Kích thước của y_test:", y_test.shape)


Kích thước của X_train: (105, 4)
Kích thước của X_test: (45, 4)
Kích thước của y_train: (105,)
Kích thước của y_test: (45,)
